server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: microshop1
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
