spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: microshop1
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: product-service

server:
  port: 8082
